### ISSUE TITLE
TODO-liste

### ISSUE THREAD

**Issue by mikini** [mikini/oeffe-website#1]
- [x] Tilmeldingsformular fungerer 
- [x] Opstøv og tilføj vedtægter
- [ ] Lav bestillingsformular der adskiller vareforbrug og betalingsidentifikation  
- [x] Migrer til øffe.dk når domænet bliver tilgængeligt
- [ ] Evaluer og test eggplant.dk (DØFF's system til administration af fødevarefællesskaberer)
